version: "3.7"
services:

    # PHP service
    app:
        build: ./app
        container_name: app
        working_dir: /var/www/
        restart: unless-stopped
        environment:
            SERVICE_NAME: app-symfony
            SERVICE_TAGS: dev
        volumes:
            - ./app:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - db

    # MariaDB database service
    db:
        image: mariadb:10.5.8
        container_name: mariadb-symfony-app
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        volumes:
            -  ./db:/var/lib/mysql/
            - ./mariadb/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
