version: "3.7"
services:

    # PHP service
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network
    
    # Node service
    node:
        build:
            context: ./app-node
            target: dev
        volumes:
            - .:/src
        command: npm start
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: development
            DEBUG: nodejs-docker-express:*

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
